#ifndef REACH_FEATURES_COMMON_FEATURE_ACTION_H
#define REACH_FEATURES_COMMON_FEATURE_ACTION_H

#ifdef __cplusplus
extern "C"
{
#endif

    typedef enum reach_feature_action_kind
    {
        REACH_FEATURE_ACTION_NONE = 0,

        REACH_FEATURE_ACTION_CLOSE_SELF,

        REACH_FEATURE_ACTION_OPEN_PINNED_APP,
        REACH_FEATURE_ACTION_OPEN_PINNED_APP_BY_ID,
        REACH_FEATURE_ACTION_LAUNCH_NEW_INSTANCE,
        REACH_FEATURE_ACTION_MOVE_PIN,
        REACH_FEATURE_ACTION_REBUILD_ITEMS,

        REACH_FEATURE_ACTION_FOCUS_WINDOW,
        REACH_FEATURE_ACTION_TOGGLE_WINDOW_FOCUS,
        REACH_FEATURE_ACTION_ACTIVATE_WINDOW,
        REACH_FEATURE_ACTION_CLOSE_WINDOW,
        REACH_FEATURE_ACTION_MINIMIZE_ALL_WINDOWS,

        REACH_FEATURE_ACTION_MEDIA_CONTROL,
        REACH_FEATURE_ACTION_ACTIVATE_TRAY_ITEM,
        REACH_FEATURE_ACTION_CYCLE_INPUT_LANGUAGE,
        REACH_FEATURE_ACTION_OPEN_SETTINGS_APP,
        REACH_FEATURE_ACTION_EXECUTE_MENU_COMMAND,

        REACH_FEATURE_ACTION_OPEN_SEARCH_RESULT,
        REACH_FEATURE_ACTION_REVEAL_SEARCH_RESULT,

        REACH_FEATURE_ACTION_CLEAR_CLIPBOARD,
        REACH_FEATURE_ACTION_REMOVE_CLIPBOARD_ITEM,
        REACH_FEATURE_ACTION_RESTORE_CLIPBOARD_ITEM
    } reach_feature_action_kind;

#define REACH_FEATURE_ACTION_FLAG_DEFER_UNTIL_CLOSED (1u << 0)

#define REACH_FEATURE_ACTION_PRIVATE_BASE 0x1000u

#ifdef __cplusplus
}
#endif

#endif
