#ifndef REACH_CORE_MENU_COMMANDS_H
#define REACH_CORE_MENU_COMMANDS_H

#ifdef __cplusplus
extern "C"
{
#endif

#define REACH_CONTEXT_MENU_MAX_ITEMS 6

    typedef enum reach_context_menu_command
    {
        REACH_CONTEXT_MENU_COMMAND_UNPIN = 100,
        REACH_CONTEXT_MENU_COMMAND_CLOSE = 101,
        REACH_CONTEXT_MENU_COMMAND_OPEN_NEW = 102,
        REACH_CONTEXT_MENU_COMMAND_PIN = 103,
        REACH_CONTEXT_MENU_COMMAND_OPEN_AS_ADMIN = 105,
        REACH_CONTEXT_MENU_COMMAND_POWER_LOCK = 200,
        REACH_CONTEXT_MENU_COMMAND_POWER_SLEEP = 201,
        REACH_CONTEXT_MENU_COMMAND_POWER_RESTART = 202,
        REACH_CONTEXT_MENU_COMMAND_POWER_SHUTDOWN = 203,
        REACH_CONTEXT_MENU_COMMAND_POWER_SIGN_OUT = 204,
        REACH_CONTEXT_MENU_COMMAND_POWER_SETTINGS = 205
    } reach_context_menu_command;

#ifdef __cplusplus
}
#endif

#endif
