#ifndef REACH_TYPOGRAPHY_H
#define REACH_TYPOGRAPHY_H

#define REACH_TEXT_SIZE_XSMALL 10.0f
#define REACH_TEXT_SIZE_SMALL 11.0f
#define REACH_TEXT_SIZE_MEDIUM 13.0f
#define REACH_TEXT_SIZE_LARGE 15.0f
#define REACH_TEXT_SIZE_HEADING 22.0f
#define REACH_TEXT_SIZE_XLARGE 20.0f

#endif
